import logging
import json
import sys

from datetime import datetime, timezone


class JSONFormatter(logging.Formatter):
    """
    Formatter that outputs log records in structured JSON format.

    The formatter enriches each log entry with contextual fields including
    timestamp, log level, module name, log message, and source code line
    number. If an exception is attached to the log record, a serialized
    stack trace is also included.
    """

    def format(self, record: logging.LogRecord) -> str:
        """
        Convert a standard LogRecord into a JSON-structured string.

        Parameters:
            record (logging.LogRecord):
                The log record instance generated by the logging framework.

        Returns:
            str:
                A JSON-formatted string representing the log entry.
        """
        log_record = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "level": record.levelname,  # INFO, ERROR, WARNING
            "module": record.name,  # Name of the module/service that calls logger
            "message": record.getMessage(),
            "line": record.lineno,
        }

        # If error, log the error stack trace
        if record.exc_info:
            log_record["exception"] = self.formatException(record.exc_info)

        return json.dumps(log_record, ensure_ascii=False)


def setup_logger() -> None:
    """
    Initialize and configure the root logger for the application.

    This configuration applies globally and is intended to be executed once
    during application startup. The logger outputs only to stdout using a
    JSON formatter, ensuring compatibility with containerized logging systems
    such as Docker and cloud log aggregators.

    Returns:
        None
    """
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)

    handler = logging.StreamHandler(
        sys.stdout
    )  # Stream the log to console -> Docker can catch the log
    handler.setFormatter(JSONFormatter())

    if logger.hasHandlers():
        logger.handlers.clear()

    logger.addHandler(handler)
